Resources
{ 
	"materials/hud/leaderboard_class_boss_pyro_shiverpeak.vmt"	"file"
	"materials/hud/leaderboard_class_boss_pyro_shiverpeak.vtf"	"file"
	"materials/hud/leaderboard_class_boss_yetimachine.vmt"	"file"
	"materials/hud/leaderboard_class_boss_yetimachine.vtf"	"file"
	
	"materials/hud/leaderboard_class_demo_atomic.vmt"	"file"
	"materials/hud/leaderboard_class_demo_atomic.vtf"	"file"
	"materials/hud/leaderboard_class_demo_giant_bomber.vmt"	"file"
	"materials/hud/leaderboard_class_demo_giant_bomber.vtf"	"file"
	"materials/hud/leaderboard_class_demo_giant_bomber_healonkill.vmt"	"file"
	"materials/hud/leaderboard_class_demo_giant_bomber_healonkill.vtf"	"file"
	"materials/hud/leaderboard_class_demo_giant_rapidfire_tank.vmt"	"file"
	"materials/hud/leaderboard_class_demo_giant_rapidfire_tank.vtf"	"file"
	"materials/hud/leaderboard_class_demo_knight_bottle.vmt"	"file"
	"materials/hud/leaderboard_class_demo_knight_bottle.vtf"	"file"
	"materials/hud/leaderboard_class_demo_scatter.vmt"	"file"
	"materials/hud/leaderboard_class_demo_scatter_giant.vmt"	"file"
	"materials/hud/leaderboard_class_demo_scatter_giant.vtf"	"file"
	"materials/hud/leaderboard_class_demo_tank_charger.vmt"	"file"
	"materials/hud/leaderboard_class_demo_tank_charger.vtf"	"file"
	
	"materials/hud/leaderboard_class_heavy_healonkill_giant.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_healonkill.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_armourbreaker.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_armourbreaker.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_scatterblast.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_shotgun_scatterblast.vtf"	"file"
	
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"

	"materials/hud/leaderboard_class_pyro_gascann.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_gascann.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_gascann_explode.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_gascann_explode.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_heal.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_heal.vtf"	"file"
	
	"materials/hud/leaderboard_class_scout_fan_armoured.vmt"	"file"
	"materials/hud/leaderboard_class_scout_fan_armoured.vtf"	"file"
	"materials/hud/leaderboard_class_scout_fan_upgraded.vmt"	"file"
	"materials/hud/leaderboard_class_scout_fan_upgraded.vtf"	"file"
	"materials/hud/leaderboard_class_scout_rocket.vmt"	"file"
	"materials/hud/leaderboard_class_scout_rocket.vtf"	"file"
	"materials/hud/leaderboard_class_scout_superbonk.vmt"	"file"
	"materials/hud/leaderboard_class_scout_superbonk.vtf"	"file"
	
	"materials/hud/leaderboard_class_shotgun_plasma.vmt"	"file"
	"materials/hud/leaderboard_class_shotgun_plasma.vtf"	"file"
	
	"materials/hud/leaderboard_class_sniper_ap.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_ap.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_bow_giant.vmt" "file"
	"materials/hud/leaderboard_class_sniper_bow_ignite.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_bow_ignite.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_carbine.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_carbine.vtf"	"file"
	
	"materials/hud/leaderboard_class_soldier_barrage_hyper.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_barrage_hyper.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_burstfire_healonkill.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_burstfire_healonkill.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_dumpster.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_dumpster.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_dumpster_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_nuker.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_nuker_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_nuker.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_rocketrain.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_rocketrain_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_rocketrain.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_spammer_burstfire.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_spammer_burstfire.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_stun.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_stun.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_titanium_armour.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_titanium_armour.vtf"	"file"
	
	"materials/hud/leaderboard_class_special_burstwave.vmt"	"file"
	"materials/hud/leaderboard_class_special_burstwave.vtf"	"file"
	"materials/hud/leaderboard_class_special_oilslick.vmt"	"file"
	"materials/hud/leaderboard_class_special_oilslick.vtf"	"file"
}